#!/bin/sh
# chkconfig: 345 99 1
# description: COVID19 MAP API SERVER (STAGING)
# processname: covid19map_server_staging

APP_DIR="/usr/share/nginx/nodeapp/staging/map_infections"
INST_DIR="install/staging"
DIRNAME="covid19map_server_staging"
EXE_USER="appuser"
LOG_LEVEL=1

export HOME=/home/$EXE_USER

if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
else
  exit 1
fi

cd $APP_DIR
case $1 in
  start)
    su -c "forever start $INST_DIR/forever_server.json" $EXE_USER
  ;;
  stop)
    su -c "forever stop `cat /run/$DIRNAME/server.pid`" $EXE_USER
  ;;
  restart)
    su -c "forever restart `cat /run/$DIRNAME/server.pid`" $EXE_USER
  ;;
  status)
    su -c "forever list|grep -E '$DIRNAME' --color=never" $EXE_USER
  ;;
  *)
    exit
  ;;
esac

