name: Server-CI-makedata

on:
  push:
    paths-ignore:
      - 'json/**'

  # masterブランチのみ、PRでCIを走らせる
  pull_request:
    paths-ignore:
      - 'json/**'
    branches:
      - master

jobs:
  makedata:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:5.0-alpine
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli -h localhost ping" --health-interval 10s --health-timeout 5s --health-retries 15
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: install sqlite3
        run: |
          sudo apt install libsqlite3-dev
          dpkg -L libsqlite3-dev
      - name: install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install git
        uses: actions/checkout@v2
      - name: Makedata
        run: |
          npm i
          npm run server_ci
      - name: sync repository
        run: |
          git config --global user.email "aida@shizentai-factory.com"
          git config --global user.name "Takeshi Aida (CI)"
          git add -f json/cache/東京都/*.csv json/cache/徳島県/*.pdf
          git commit -m 'Update by GitHub Actions'
          git push --force-with-lease origin ${GITHUB_REF##*/}

