name: Server-CI-makedata

on:
  push:
    paths-ignore:
      - 'json/**'
    branches:
      - master # developで走るとconflitが煩わしい

  schedule:
    - cron: "0 18 * * *" # 3:00 JST  デフォルト(master)ブランチ以外ではトリガーされない

defaults:
  run:
    shell: bash

jobs:
  makedata:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:5.0-alpine
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli -h localhost ping" --health-interval 10s --health-timeout 5s --health-retries 15
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379

    steps:
      - name: install sqlite3
        run: |
          sudo apt install libsqlite3-dev
          dpkg -L libsqlite3-dev
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version
      - name: install git
        uses: actions/checkout@v2
      - name: Makedata
        run: |
          npm i
          npm run server_ci
          cd json;source backup_data.sh;cd ..
      - name: sync repository
        continue-on-error: true
        run: |
          git config --global user.email "aida@shizentai-factory.com"
          git config --global user.name "Takeshi Aida (CI)"
          git add -f -A json/cache/東京都/*.csv json/cache/徳島県/*.pdf json/infectors.json json/log/*.json
          git commit -m 'Update by GitHub Actions'
      - if: success()
        name: push if modified
        run: |
          git push --force-with-lease origin ${GITHUB_REF##*/}

