# This is a basic workflow to help you get started with Actions

name: Server-CI-makedata

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  makedata:
    runs-on: ubuntu-latest


    services:
      redis:
        image: redis:5.0-alpine
        options: --health-cmd "redis-cli -h localhost ping" --health-interval 10s --health-timeout 5s --health-retries 15

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: install sqlite3
        run: |
          sudo apt install libsqlite3-dev
          dpkg -L libsqlite3-dev
      - name: install Node.js and packages
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        run: |
          npm i
      - name: fetch repository
        run: |
          git config --global user.email "aida@shizentai-factory.com"
          git config --global user.name "Takeshi Aida (CI)"
          git remote -v
          git status
          git fetch origin
          git checkout ${GITHUB_REF##*/}
      - name: Makedata
        run: |
          npm run server_ci
      - name: sync repository
        run: |
          git add json/cache/東京都/*.csv json/cache/徳島県/*.pdf
          git commit -m 'Update by GitHub Actions'
          git push origin ${GITHUB_REF##*/}

